owner: paion-data
repo: service-status

sites:
  - name: paion-data.com
    url: https://paion-data.com/
  - name: Entity Webservice Documentation
    url: https://entity-ws.paion-data.dev/
  - name: Tiger
    url: https://huggingface.co/spaces/paion-data/tiger
  - name: Pantex
    url: https://paion-data-pantex.hf.space/gradio_api/call/tts
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{ "data": [ "Hello!!", "Hello!!", "tts-1", "alloy", "mp3", 0.25 ]}'
  - name: Lamassu
    icon: https://huggingface.co/favicon.ico
    url: https://paion-data-lamassu.hf.space/gradio_api/call/predict
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{ "data": ["我爱中国"] }'
  - name: Wiktionary Data
    url: https://huggingface.co/datasets/paion-data/wiktionary-data
  - name: UI Component Library
    url: https://ui.paion-data.com/
  - name: FastUI
    url: https://fastui.paion-data.com/
  - name: FastSpring
    url: https://fastspring.paion-data.com/
  - name: Chatbot WS
    url: https://chatbot.paion-data.com/
  - name: hashistack
    url: https://hashistack.paion-data.dev/
  # - name: Paion Data API Gateway
  #   url:  https://api.paion-data.dev/wilhelm/languages/german?perPage=100&page=1
  #   icon: https://konghq.com/favicon.ico
  - name: Paion Data Corp Mail Service
    url: https://mail.paion-data.dev/
    icon: https://avatars.githubusercontent.com/u/15187237?s=200&v=4
  - name: (Team's Knowledge Hub) Documentation Guide
    url: https://writethedocs.paion-data.dev/
  - name: (Team's Knowledge Hub) Jest
    url: https://jest.paion-data.dev/
  - name: (Team's Knowledge Hub) ArangoDB
    url: https://arango.paion-data.dev/
  - name: (Team's Knowledge Hub) Testcontainers for Java
    url: http://testcontainers-java.paion-data.dev/
  - name: (Team's Knowledge Hub) Paion Data Docker Images
    url: https://linuxserver.paion-data.dev/
  - name: (Team's Knowledge Hub) MailHog
    url: https://mailhog.paion-data.dev/
  - name: (Team's Knowledge Hub) Git
    url: https://git.paion-data.dev/

status-website:
  cname: status.paion-data.dev
  favicon: https://paion-data.com/favicon.ico
  logoUrl: https://avatars.githubusercontent.com/u/113274132?s=200&v=4
  name: Paion Data Services
  introTitle: "Welcome to Paion Data's home for real-time and historical data on system performance."
  introMessage: This is the status page our our use-facing sites which uses **real-time** data from our [GitHub organization](https://github.com/paion-data).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: light

commitMessages:
  commitAuthorName: "Paion Data [bot]"
  commitAuthorEmail: "bot@paion-data.dev"

issue_author: paion-data-bot
