owner: paion-data
repo: service-status

sites:
  - name: paion-data.com
    url: https://paion-data.com/
  - name: wilhelmlang.com
    url: https://wilhelmlang.com
  - name: Alexandria
    url: https://alexandria.paion-data.com/
  - name: UI Design Hub
    url: https://ui.paion-data.com/
  - name: Paion Data API Gateway
    url:  https://api.paion-data.dev/wilhelm/languages/german?perPage=100&page=1
    icon: https://konghq.com/favicon.ico

status-website:
  cname: status.paion-data.dev
  logoUrl: https://avatars.githubusercontent.com/u/113274132?s=200&v=4
  name: Paion Data Services
  introTitle: "Welcome to Paion Data's home for real-time and historical data on system performance."
  introMessage: This is the status page our our use-facing sites which uses **real-time** data from our [GitHub organization](https://github.com/paion-data).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
