owner: paion-data
repo: service-status

sites:
  - name: paion-data.com
    url: https://paion-data.com/
  - name: wilhelmlang.com
    url: https://wilhelmlang.com
  - name: Paion Data API Gateway
    url:  https://api.paion-data.dev/wilhelm/languages/german?perPage=100&page=1
    icon: https://private-avatars.githubusercontent.com/u/962416?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MzQ1NzU0NjAsIm5iZiI6MTczNDU3NDI2MCwicGF0aCI6Ii91Lzk2MjQxNiJ9.u5hJ7HVBg44lnqc2GjKCDp10skqMiZZ_qtZ1tIhDgdI&s=48&v=4

status-website:
  cname: status.paion-data.dev
  logoUrl: https://avatars.githubusercontent.com/u/113274132?s=200&v=4
  name: Paion Data Services
  introTitle: "Welcome to Paion Data's home for real-time and historical data on system performance."
  introMessage: This is the status page our our use-facing sites which uses **real-time** data from our [GitHub organization](https://github.com/paion-data).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
