owner: paion-data
repo: service-status

sites:
  - name: nexusgraph.com
    url: https://nexusgraph.com/
    icon: https://paion-data.github.io/nexusgraph.com/favicon.ico
  - name: paion-data.com
    url: https://paion-data.com/
  - name: Paion Data CI/CD platform
    url: https://ci-cd.paion-data.dev/
  - name: Paion Data Software Artifactory
    url: https://artifactory.paion-data.dev/
  - name: Paion Data Docker Registry
    url: https://hub.paion-data.dev/
  - name: Astraios
    url: https://astraios.io
  - name: Immutable Infrastructure as a Service
    url: https://immutable-infrastructure.com

status-website:
  cname: status.paion-data.dev
  logoUrl: https://avatars.githubusercontent.com/u/113274132?s=200&v=4
  name: Paion Data Services
  introTitle: "Welcome to Paion Data's home for real-time and historical data on system performance."
  introMessage: This is the status page our our use-facing sites which uses **real-time** data from our [GitHub organization](https://github.com/paion-data).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
