owner: paion-data
repo: service-status

sites:
  - name: paion-data.com
    url: https://paion-data.com/
  - name: wilhelmlang.com
    url: https://wilhelmlang.com
  - name: VK-45.01
    url: https://vk4501.paion-data.com/
  - name: Alexandria
    url: https://alexandria.paion-data.com/
  - name: Tiger
    url: https://huggingface.co/spaces/paion-data/tiger
  - name: Aristotle
    url: https://huggingface.co/spaces/paion-data/aristotle
  - name: Lamassu
    method: POST
    url: https://paion-data-lamassu.hf.space/gradio_api/call/predict
    headers:
      - "Content-Type: application/json"
    body: '{ "data": ["我爱中国"] }'
  - name: Wiktionary Data
    url: https://huggingface.co/datasets/paion-data/wiktionary-data
  - name: UI Component Library
    url: https://ui.paion-data.com/
  - name: FastUI
    url: https://fastui.paion-data.com/
  - name: Bertok
    url: https://bertok.wilhelmlang.com/
  - name: FastSpring
    url: https://fastspring.paion-data.com/
  - name: Paion Data API Gateway
    url:  https://api.paion-data.dev/wilhelm/languages/german?perPage=100&page=1
    icon: https://konghq.com/favicon.ico
  - name: hashistack
    url: https://hashistack.paion-data.dev/

status-website:
  cname: status.paion-data.dev
  logoUrl: https://avatars.githubusercontent.com/u/113274132?s=200&v=4
  name: Paion Data Services
  introTitle: "Welcome to Paion Data's home for real-time and historical data on system performance."
  introMessage: This is the status page our our use-facing sites which uses **real-time** data from our [GitHub organization](https://github.com/paion-data).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
